from enum import StrEnum


class DutyStatus(StrEnum):
    OFF_DUTY = "OFF_DUTY"
    SLEEPER_BERTH = "SLEEPER_BERTH"
    DRIVING = "DRIVING"
    ON_DUTY_NOT_DRIVING = "ON_DUTY_NOT_DRIVING"


class EventType(StrEnum):
    DRIVE = "DRIVE"
    PICKUP = "PICKUP"
    DROPOFF = "DROPOFF"
    FUEL = "FUEL"
    BREAK_30_MIN = "BREAK_30_MIN"
    DAILY_REST_10_HOUR = "DAILY_REST_10_HOUR"
    CYCLE_RESTART_34_HOUR = "CYCLE_RESTART_34_HOUR"
    REPORTED_DELAY = "REPORTED_DELAY"
