import { expect, test } from '@playwright/test'

test('sample trip reaches map, itinerary, and daily logs', async ({ page }) => {
  const browserErrors: string[] = []
  page.on('pageerror', (error) => browserErrors.push(error.message))
  page.on('console', (message) => {
    if (message.type() === 'error') browserErrors.push(message.text())
  })
  await page.goto('/')
  await page.getByRole('button', { name: 'Switch to light theme' }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
  await page.getByRole('button', { name: 'Switch to dark theme' }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await page.getByRole('button', { name: 'Choose pickup on map' }).click()
  const picker = page.getByRole('dialog', { name: /choose pickup on the map/i })
  await expect(picker).toBeVisible()
  await expect(picker.getByText(/US locations only/i)).toBeVisible()
  await page.getByRole('button', { name: 'Cancel' }).click()
  await page.getByRole('button', { name: 'Load sample trip' }).click()
  await page.getByRole('button', { name: 'Build trip plan' }).click()
  await expect(page.getByText(/Plan ready/)).toBeVisible()
  await expect(page.getByText('Ending cycle used')).toBeVisible()
  await expect(page.getByLabel('Trip plan sections')).toBeVisible()
  await expect(page.getByLabel('Map legend').getByText('current location')).toBeVisible()
  await page.getByRole('tab', { name: 'Itinerary' }).click()
  await expect(page.getByText('PICKUP', { exact: true })).toBeVisible()
  await expect(page.getByLabel(/Duty totals for/).first()).toContainText('driving:')
  await page.getByRole('tab', { name: 'Daily logs' }).click()
  await expect(page.locator('.logs').getByText(/Driver's daily log/)).toBeVisible()
  await page.getByRole('button', { name: 'Inspect log full screen' }).click()
  await expect(page.getByRole('dialog', { name: 'Daily log inspection' })).toBeVisible()
  await page.getByRole('button', { name: 'Close' }).click()
  await expect(page.locator('.print-logs article')).toHaveCount(3)
  await page.evaluate(() => {
    window.print = () => document.body.setAttribute('data-print-invoked', 'true')
  })
  await page.getByRole('button', { name: 'Print logs' }).click()
  await expect(page.locator('body')).toHaveAttribute('data-print-invoked', 'true')

  await page.getByRole('button', { name: 'Replan from progress' }).click()
  const replan = page.getByRole('dialog', { name: 'Replan from reported progress' })
  await expect(replan).toBeVisible()
  await expect(replan.getByText(/driver-reported progress, not a verified ELD record/i)).toBeVisible()
  await replan.getByLabel('Last completed event').click()
  await page.getByRole('option', { name: /PICKUP/ }).click()
  await replan.getByLabel('Current US location').fill('Denver, CO')
  await replan.getByRole('button', { name: 'Build updated plan' }).click()

  await expect(page.getByText(/Plan ready.*version 2/i)).toBeVisible()
  await expect(page.getByText(/Driver-reported checkpoint:/i)).toBeVisible()
  await page.getByRole('tab', { name: 'Itinerary' }).click()
  await expect(page.getByText('reported complete', { exact: true }).first()).toBeVisible()
  await page.getByRole('button', { name: 'View original' }).click()
  await expect(page.getByText(/Plan ready.*version 1/i)).toBeVisible()
  await page.getByRole('button', { name: 'View updated' }).click()
  await expect(page.getByText(/Plan ready.*version 2/i)).toBeVisible()
  await page.getByRole('button', { name: 'Edit trip' }).click()
  await expect(page.getByRole('combobox', { name: /^current location$/i })).toHaveValue('Chicago, IL')
  expect(browserErrors).toEqual([])
})
